### ISSUE TITLE
Use COMMON_WIKIPAGE_SAVE

### ISSUE THREAD

**Issue by mallchin** [mallchin/dokuwiki-slack-notifier#1]
DokuWiki have introduced a new hook, COMMON_WIKIPAGE_SAVE, which will be much more useful for this plugin.

Migrate to use COMMON_WIKIPAGE_SAVE as and when it becomes available.

**Comment by glensc** [comment]
I plan to deal with this in my fork at some point:
- https://github.com/glensc/dokuwiki-plugin-slacknotifier

I think the changes can be adapted from here:
- https://github.com/zteeed/dokuwiki-discord-notifier/pull/1/files

**Comment by glensc** [comment]
Refactored:
- https://github.com/glensc/dokuwiki-plugin-slacknotifier/pull/5

**Comment by mallchin** [comment]
Closing in favour of https://github.com/glensc/dokuwiki-plugin-slacknotifier.
