### ISSUE TITLE
Compare changes always links to newest page

### ISSUE THREAD

**Issue by mallchin** [mallchin/dokuwiki-slack-notifier#3]
The compare changes link shows differences between the old revision and the latest revision rather than the old revision and the new revision.  This is a subtle difference but it means compare changes links do not show relevant differences once newer revisions are written.

**Comment by glensc** [comment]
Fixed with https://github.com/glensc/dokuwiki-plugin-slacknotifier/pull/9

**Comment by mallchin** [comment]
Closing in favour of https://github.com/glensc/dokuwiki-plugin-slacknotifier.
