### ISSUE TITLE
Links Not Working

### ISSUE THREAD

**Issue by dinosaw** [mallchin/dokuwiki-slack-notifier#4]
When a change is made on my DokuWiki install, the hyperlink is not being created in Slack's channel. Instead of a clickable URL, it instead shows the raw text like this:

```
dinosaw updated page <games/bin/2|games:bin:2> (<games/bin/2|Compare changes>)
```

Relevant Information:
- DokuWiki Version: Release 2016-06-26a "Elenor of Tsort"
- Plugin Version: Latest
- Using nice URLs (.htaccess)
- Using slash as namespace separator in URLs
- Page name word separator is `-`

**Comment by george-viaud** [comment]
Having the same experience.

Likely somewhere in _get_url() method

**Comment by CvH** [comment]
You can use the Dokuwiki Rocketchat plugin, just fill in the Slack Webhook instead of the Rocketchat Webhook url and it works :)

**Comment by glensc** [comment]
Fixed with:
- https://github.com/glensc/dokuwiki-plugin-slacknotifier/pull/5

it uses wiki `wl()` function now.

**Comment by mallchin** [comment]
Closed in favour of https://github.com/glensc/dokuwiki-plugin-slacknotifier.
