### ISSUE TITLE
Extension Manager Showing Available Update

### ISSUE THREAD

**Issue by dinosaw** [mallchin/dokuwiki-slack-notifier#5]
Whether or not I do a manual install via git or an automatic install by the Extension Manager in my DokuWiki install, it keeps saying `Update: New version 2016-06-13 is available`. When I choose to update the plugin, it says `Plugin slacknotifier updated successfully` but still continues to show the available update message.

http://i.imgur.com/Rc7bWon.png

**Comment by george-viaud** [comment]
Confirmed, same experience here.

**Comment by caotu** [comment]
i have same error.

**Comment by glensc** [comment]
outdated. no longer relevant

**Comment by mallchin** [comment]
Closed in favour of https://github.com/glensc/dokuwiki-plugin-slacknotifier.
